version: '3.7'
services:
  redis:
    container_name: coupon-redis
    image: redis:7.2-alpine
    restart: always
    command: redis-server --port 6380
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6380:6380
  mysql:
    container_name: coupon-mysql
    image: ubuntu/mysql:edge
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=coupon
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1235
      - MYSQL_ROOT_PASSWORD=1235
      - TZ=UTC
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d